dbt_snowflake_demo:
  target: dev
  outputs:
    dev:      
      type: snowflake
      account: "{{ env_var('DBT_PROFILE_SNOWFLAKE_ACCOUNT') }}"
      user: HIROKIIGETA
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: ACCOUNTADMIN


      database: analytics
      warehouse: COMPUTE_WH
      schema: dbt_hiro
      threads: 4
      client_session_keep_alive: False
      # query_tag: [anything]

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false 
      retry_all: False  # default: false 
